const $=s=>document.querySelector(s);
let running=false,rpm=0,target=0,gear=0,mode="comfort",muted=false,last=performance.now();
let speed=0,brake=0,decel=false,audio=null;
const max=10000,red=9500,ratios=[0,3,2.1,1.55,1.18,.92,.72,.58];
const zones=[900,2100,3300,4700,6100,7600,9000];
const files=zones.map((_,i)=>`assets/audio/v12_${i}.mp3`);
const rpmEl=$("#rpm"),needle=$("#needle"),throttle=$("#throttle"),throttleValue=$("#throttleValue"),throttleValue2=$("#throttleValue2");
for(let i=0;i<=20;i++){let x=document.createElement("div");x.className="tick"+(i%2===0?" major":"")+(i>=17?" red":"");x.style.transform=`translate(-50%,-50%) rotate(${-132+i*13.2}deg)`;$("#ticks").append(x)}
function factor(){return mode==="comfort"?.72:mode==="sport"?1:1.28}
function ensureAudio(){if(audio)return audio;const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;const ctx=new C();const master=ctx.createGain(),filter=ctx.createBiquadFilter();filter.type="lowpass";filter.frequency.value=2200;filter.Q.value=.35;master.gain.value=0;filter.connect(master).connect(ctx.destination);audio={ctx,master,filter,sources:[],buffers:[],ready:false};
Promise.all(files.map(f=>fetch(f).then(r=>r.arrayBuffer()).then(b=>ctx.decodeAudioData(b)))).then(buffers=>{audio.buffers=buffers;buffers.forEach((buf,i)=>{const src=ctx.createBufferSource(),g=ctx.createGain();src.buffer=buf;src.loop=true;src.loopStart=.35;src.loopEnd=Math.max(.5,buf.duration-.35);g.gain.value=0;src.connect(g).connect(filter);src.start(0);audio.sources.push({src,g,zone:zones[i]})});audio.ready=true}).catch(e=>console.warn("V12 audio load failed",e));return audio}
function audioLevel(){if(!audio||!audio.ready)return;const now=audio.ctx.currentTime;const r=Math.max(0,rpm);audio.sources.forEach((s,i)=>{const dist=Math.abs(r-s.zone);let w=Math.max(0,1-dist/1500);if(i===0)w=Math.max(w,r<1800?1:0);if(i===audio.sources.length-1)w=Math.max(w,r>8200?1:0);let level=running?(0.022+Number(throttle.value)/100*.085):(0);if(decel)level*=.65;s.g.gain.setTargetAtTime(muted?0:level*w,now,.055);const rate=Math.max(.72,Math.min(1.32,r/Math.max(400,s.zone)));s.src.playbackRate.setTargetAtTime(rate,now,.05)});audio.filter.frequency.setTargetAtTime(1500+r*.55,now,.08);audio.master.gain.setTargetAtTime(muted?0:1,now,.03)}
function triggerShift(){if(!audio||!audio.ready||muted)return;const idx=Math.min(6,Math.max(0,Math.round(rpm/1500)));const s=audio.buffers[idx];const src=audio.ctx.createBufferSource(),g=audio.ctx.createGain();src.buffer=s;src.playbackRate.value=Math.max(.8,Math.min(1.45,rpm/zones[idx]));g.gain.setValueAtTime(.0001,audio.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.06,audio.ctx.currentTime+.025);g.gain.exponentialRampToValueAtTime(.0001,audio.ctx.currentTime+.34);src.connect(g).connect(audio.filter);src.start();src.stop(audio.ctx.currentTime+.36)}
function setRun(v){running=v;if(v){const a=ensureAudio();a?.ctx.resume();target=Math.max(900,rpm||900);$("#start").classList.add("running");$("#start span").textContent="STOP ENGINE";$("#trackStart").textContent="STOP";$("#state").textContent="RUNNING";$(".state").classList.add("running");setTimeout(()=>{if(audio?.ctx.state==="suspended")audio.ctx.resume()},100)}else{target=0;$("#start").classList.remove("running");$("#start span").textContent="START ENGINE";$("#trackStart").textContent="START";$("#state").textContent="STANDBY";$(".state").classList.remove("running");throttle.value=0;setThrottle(0);brake=0;decel=false}}
$("#start").onclick=()=>setRun(!running);$("#trackStart").onclick=()=>setRun(!running);
function setThrottle(v){v=Math.max(0,Math.min(100,v));throttle.value=v;throttleValue.textContent=v+"%";throttleValue2.textContent=v+"%";$("#trackThrottle").querySelector("b").textContent=v+"%"}
throttle.oninput=()=>setThrottle(+throttle.value);
function pedalBind(el,down,up){el.addEventListener("pointerdown",e=>{e.preventDefault();el.classList.add("pressed");down()});["pointerup","pointercancel","pointerleave"].forEach(ev=>el.addEventListener(ev,e=>{el.classList.remove("pressed");up()}))}
pedalBind($("#decelPedal"),()=>decel=true,()=>decel=false);pedalBind($("#trackDecel"),()=>decel=true,()=>decel=false);
pedalBind($("#brakePedal"),()=>brake=100,()=>brake=0);pedalBind($("#trackBrake"),()=>brake=100,()=>brake=0);
pedalBind($("#throttlePedal"),()=>setThrottle(100),()=>setThrottle(0));pedalBind($("#trackThrottle"),()=>setThrottle(100),()=>setThrottle(0));
$("#brakePedal").querySelector("b").textContent="0%";
$("#trackBrake").querySelector("b").textContent="0%";
document.querySelectorAll(".modeBtn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".modeBtn").forEach(x=>x.classList.remove("active"));b.classList.add("active");mode=b.dataset.mode;$("#modeName").textContent=b.textContent;$("#trackMode").textContent=b.textContent});
function shift(d){if(!running)return;if(d>0&&gear<7){gear++;target=Math.max(1500,rpm*.62);triggerShift();flash("UPSHIFT")}if(d<0&&gear>1){gear--;target=Math.min(red,rpm*1.42+650);triggerShift();flash("DOWNSHIFT")}}
function flash(t){$("#shift").textContent=t;setTimeout(()=>$("#shift").textContent="READY",420)}
$("#up").onclick=$("#trackUp").onclick=()=>shift(1);$("#down").onclick=$("#trackDown").onclick=()=>shift(-1);
$("#mute").onclick=()=>{muted=!muted;$("#mute").textContent=muted?"SOUND OFF":"SOUND ON"};
function render(){const ratio=ratios[Math.max(gear,1)];let desiredSpeed=gear?Math.min(300,rpm/10000*300*(ratio/3)) : 0;speed += (desiredSpeed-speed)*.06;speed=Math.max(0,speed-(brake?2.8:0)*.16);let temp=running?Math.round(78+rpm/90):"--",oil=running?Math.round(74+rpm/105):"--",p=running?Math.round(90+rpm/10000*680*(+throttle.value/100)):"--";rpmEl.textContent=Math.round(rpm).toString().padStart(4,"0");needle.style.transform=`translate(-50%,-100%) rotate(${-132+rpm/max*264}deg)`;$("#speed").textContent=Math.round(speed).toString().padStart(3,"0");$("#gear").textContent=gear?gear:"N";$("#engineTemp").textContent=temp+" °C";$("#oilTemp").textContent=oil+" °C";$("#oilPressure").textContent=running?(1.2+rpm/4200).toFixed(1)+" bar":"-- bar";$("#power").textContent=p+" HP";$("#trackRpm").textContent=rpmEl.textContent;$("#trackSpeed").textContent=Math.round(speed).toString().padStart(3,"0");$("#trackGear").textContent=gear?gear:"N";$("#trackTemp").textContent=temp+"°C";$("#trackOil").textContent=oil+"°C";$("#trackPower").textContent=p+" HP";$("#rpmBar").style.width=(rpm/max*100)+"%";$("#brakePedal b").textContent=brake+"%";$("#trackBrake b").textContent=brake+"%"}
function loop(t){let dt=Math.min(.05,(t-last)/1000);last=t;if(running){const th=+throttle.value;if(th>0)target=Math.min(red,900+th*factor()*78);else if(decel)target=Math.max(900,rpm-6200*dt);else target=Math.max(900,rpm-3000*dt);if(brake)target=Math.max(900,target-2500*dt);rpm += (target-rpm)*Math.min(1,5.2*dt);if(rpm>=red){rpm=red;target=red;flash("LIMITER")}}else{rpm=Math.max(0,rpm-5200*dt);speed=Math.max(0,speed-80*dt);if(rpm<50)gear=0}render();audioLevel();requestAnimationFrame(loop)}requestAnimationFrame(loop);
document.addEventListener("keydown",e=>{if(e.code==="Space"){e.preventDefault();setRun(!running)}if(e.key==="ArrowRight")shift(1);if(e.key==="ArrowLeft")shift(-1);if(e.key==="ArrowUp")setThrottle(100);if(e.key==="ArrowDown")setThrottle(0)});
